-- Dimension table 
DROP TABLE IF EXISTS alerts CASCADE;
DROP TABLE IF EXISTS continent CASCADE;
DROP TABLE IF EXISTS country CASCADE;
DROP TABLE IF EXISTS stations CASCADE;
DROP TABLE IF EXISTS sensors CASCADE;
DROP TABLE IF EXISTS update_control CASCADE;
DROP TABLE IF EXISTS weather_alerts CASCADE;

-- measurements tables 
DROP TABLE IF EXISTS measurements CASCADE;
DROP TABLE IF EXISTS forecast CASCADE;


